CREATE TABLE `bookings` (
 `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 `booking_reference` varchar(255) DEFAULT NULL,
 `status` enum('pending_payment','confirmed','in_progress','completed','cancelled') DEFAULT NULL,
 `student_id` bigint(20) unsigned NOT NULL,
 `teacher_id` bigint(20) unsigned NOT NULL,
 `course_id` bigint(20) unsigned DEFAULT NULL,
 `subject_id` bigint(20) unsigned DEFAULT NULL,
 `language_id` bigint(20) unsigned DEFAULT NULL,
 `order_id` bigint(20) unsigned DEFAULT NULL,
 `session_type` enum('single','package') DEFAULT NULL,
 `sessions_count` int(11) DEFAULT 1,
 `sessions_completed` int(11) DEFAULT 0,
 `first_session_date` date DEFAULT NULL,
 `first_session_start_time` time DEFAULT NULL,
 `first_session_end_time` time DEFAULT NULL,
 `session_duration` int(11) DEFAULT NULL,
 `price_per_session` decimal(10,2) DEFAULT NULL,
 `subtotal` decimal(10,2) DEFAULT NULL,
 `discount_percentage` decimal(5,2) DEFAULT 0.00,
 `discount_amount` decimal(10,2) DEFAULT 0.00,
 `total_amount` decimal(10,2) DEFAULT NULL,
 `currency` varchar(3) DEFAULT 'SAR',
 `special_requests` text DEFAULT NULL,
 `booking_date` datetime DEFAULT NULL,
 `cancellation_reason` varchar(255) DEFAULT NULL,
 `cancelled_at` datetime DEFAULT NULL,
 `refund_amount` decimal(10,2) DEFAULT NULL,
 `refund_percentage` decimal(5,2) DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT NULL,
 `updated_at` timestamp NULL DEFAULT NULL,
 `timeslot_id` int(11) DEFAULT NULL,
 `service_id` int(11) NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `booking_reference` (`booking_reference`),
 KEY `idx_student_status` (`student_id`,`status`),
 KEY `idx_teacher_status` (`teacher_id`,`status`),
 KEY `bookings_course_id_foreign` (`course_id`),
 KEY `fk_orders_id` (`order_id`),
 CONSTRAINT `bookings_course_id_foreign` FOREIGN KEY (`course_id`) REFERENCES `courses` (`id`) ON DELETE CASCADE,
 CONSTRAINT `bookings_student_id_foreign` FOREIGN KEY (`student_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 CONSTRAINT `bookings_teacher_id_foreign` FOREIGN KEY (`teacher_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 CONSTRAINT `fk_orders_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci